import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MaxWidthRapper } from '@/components/MaxWidthRapper'
import { Navbar } from '@/components/Navbar'
import { cn } from '@/lib/utils'
import Providers from '@/components/Providers'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <Providers>
      <body className={cn("grainy",inter.className)}>
        <Navbar/>
      
        <MaxWidthRapper classname='p-2'>
        {children}
        
        </MaxWidthRapper>
        <Toaster/>
      </body>
      </Providers>
    </html>
  )
}
